var searchData=
[
  ['a_20failed_20workflow_0',['4.4. Demonstration of a failed workflow',['../MicroSpeech.html#autotoc_md21',1,'']]],
  ['a_20href_20https_3a_20github_20com_20cdr_20code_20server_20code_20server_20a_20visual_20studio_20code_1',['2.4. [Optional] Enable &lt;a href=&quot;https://github.com/cdr/code-server&quot; &gt;Code Server&lt;/a&gt; (Visual Studio Code)',['../MicroSpeech.html#autotoc_md9',1,'']]],
  ['a_20visual_20studio_20code_2',['2.4. [Optional] Enable &lt;a href=&quot;https://github.com/cdr/code-server&quot; &gt;Code Server&lt;/a&gt; (Visual Studio Code)',['../MicroSpeech.html#autotoc_md9',1,'']]],
  ['accessing_20and_20launching_20the_20ami_3',['2. Accessing and launching the AMI',['../MicroSpeech.html#autotoc_md5',1,'']]],
  ['actions_4',['Actions',['../MicroSpeech.html#autotoc_md17',1,'4. Automated CI/CD with GitHub Actions'],['../MicroSpeech.html#autotoc_md18',1,'4.1. Configure GitHub Actions']]],
  ['actions_20setup_5',['GitHub Actions setup',['../GetStarted.html#GS_GitHub_Setup',1,'']]],
  ['actions_20workflow_6',['4.3. GitHub Actions workflow',['../MicroSpeech.html#autotoc_md20',1,'']]],
  ['alternative_20launch_20the_20ami_20from_20aws_20ec2_7',['2.2. (Alternative) Launch the AMI from AWS EC2',['../MicroSpeech.html#autotoc_md7',1,'']]],
  ['ami_8',['AMI',['../MicroSpeech.html#autotoc_md5',1,'2. Accessing and launching the AMI'],['../MicroSpeech.html#autotoc_md13',1,'3.2. Build example within the AMI'],['../MicroSpeech.html#autotoc_md19',1,'4.2. Setup runner on AMI']]],
  ['ami_20console_9',['2.3. Enable AMI console',['../MicroSpeech.html#autotoc_md8',1,'']]],
  ['ami_20from_20aws_20ec2_10',['2.2. (Alternative) Launch the AMI from AWS EC2',['../MicroSpeech.html#autotoc_md7',1,'']]],
  ['ami_20on_20aws_20marketplace_11',['2.1. Find AMI on AWS Marketplace',['../MicroSpeech.html#autotoc_md6',1,'']]],
  ['analyze_20failures_12',['Analyze failures',['../GetStarted.html#GS_AnalyseFailure',1,'']]],
  ['and_20build_20example_13',['3. Import and build example',['../MicroSpeech.html#autotoc_md11',1,'']]],
  ['and_20clone_20example_14',['3.1. Fork and clone example',['../MicroSpeech.html#autotoc_md12',1,'']]],
  ['and_20experimental_15',['Legacy and experimental',['../examples_beta.html',1,'']]],
  ['and_20launching_20the_20ami_16',['2. Accessing and launching the AMI',['../MicroSpeech.html#autotoc_md5',1,'']]],
  ['arm_20virtual_20hardware_17',['Getting Started with Micro speech on Arm Virtual Hardware',['../MicroSpeech.html#autotoc_md3',1,'']]],
  ['ats_20keyword_20example_18',['ATS-Keyword Example',['../ATS-Keyword.html',1,'examples_beta']]],
  ['automated_20ci_20cd_20with_20github_20actions_19',['4. Automated CI/CD with GitHub Actions',['../MicroSpeech.html#autotoc_md17',1,'']]],
  ['aws_20ec2_20',['2.2. (Alternative) Launch the AMI from AWS EC2',['../MicroSpeech.html#autotoc_md7',1,'']]],
  ['aws_20iot_20thing_21',['Create AWS IoT Thing',['../aws_mqtt.html#aws_iot_thing',1,'']]],
  ['aws_20marketplace_22',['2.1. Find AMI on AWS Marketplace',['../MicroSpeech.html#autotoc_md6',1,'']]],
  ['aws_20mqtt_20example_23',['AWS MQTT Example',['../aws_mqtt.html',1,'examples_beta']]],
  ['aws_20setup_24',['AWS setup',['../GetStarted.html#GS_AWS_Setup',1,'']]]
];
